config/routes.rb
Rails.application.routes.draw do
 
  resources :participations
  resources :locations
  resources :tournaments
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :rec_password, :only => [:new, :create]

  root 'tournaments#index'

  match '/signup', to: 'users#new', via:'get'
  match '/signin', to: 'sessions#new', via:'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/verify', to: 'users#accountVerification', via: 'get'
  match '/pass', to: 'rec_password#new', via: 'get'
  match '/reset', to: 'rec_password#reset', via: 'get'
  match '/resetAction', to: 'rec_password#resetAction', via: 'post'
  match '/sponsor', to: 'tournaments#sponsor', via: 'post'
  match '/sponsor/:id', to: 'tournaments#sponsorDelete', via: 'delete'
  match '/join', to: 'tournaments#new_join', via: 'get'
  match '/join', to: 'tournaments#create_join', via: 'post'
  match '/participation/:id', to: 'tournaments#leftTournament', via: 'delete'
  match '/my_tournaments', to: 'tournaments#my', via: 'get'
  match '/start', to: 'tournaments#start', via: 'get'
  match '/matches', to: 'tournaments#showMatches', via: 'get' 
  match '/nextRound', to: 'tournaments#nextRound', via: 'post'
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  validates :license, :ranking, presence: true
  validates :license, :ranking, numericality: { greater_than: 0 }
  validates_uniqueness_of :license, scope: :tournament_id
  validates_uniqueness_of :ranking, scope: :tournament_id
  validates_uniqueness_of :user_id, scope: :tournament_id
  has_many :matches
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: [:show, :edit, :update, :destroy]

  # GET /participations
  # GET /participations.json
  def index
    @participations = Participation.all
  end

  # GET /participations/1
  # GET /participations/1.json
 def show
  end

  # GET /participations/new
  def new
    @participation = Participation.new
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations
  # POST /participations.json
  def create
    @participation = Participation.new(participation_params)

    respond_to do |format|
      if @participation.save
        format.html { redirect_to @participation, notice: 'Participation was successfully created.' }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participations/1
  # PATCH/PUT /participations/1.json
  def update
    params[:user_id] = current_user.id
    #params[:tournament_id]
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to @participation, notice: 'Participation was successfully updated.' }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1
  # DELETE /participations/1.json
  def destroy
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to participations_url, notice: 'Participation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participation_params
      params.require(:participation).permit(:user_id, :tournament_id, :license, :ranking)
    end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_for(@participation) do |f| %>
  <% if @participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
      <% @participation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :license %><br>
    <%= f.number_field :license %>
  </div>
  
  <div class="field">
    <%= f.label :ranking %><br>
    <%= f.number_field :ranking %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/participations/edit.html.erb
<h1>Editing participation</h1>

<%= render 'form' %>

<%= link_to 'Show', @participation %> |
<%= link_to 'Back', participations_path %>

app/views/participations/index.html.erb
<h1>Listing participations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Tournament</th>
      <th>License</th>
      <th>Ranking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= participation.user_id %></td>
        <td><%= participation.tournament_id %></td>
        <td><%= participation.license %></td>
        <td><%= participation.ranking %></td>
        <td><%= link_to 'Show', participation %></td>
        <td><%= link_to 'Edit', edit_participation_path(participation) %></td>
        <td><%= link_to 'Destroy', participation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participation', new_participation_path %>

app/views/participations/new.html.erb
<h1>New participation</h1>

<%= render 'form' %>

<%= link_to 'Back', participations_path %>

app/views/participations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @participation.user_id %>
</p>

<p>
  <strong>Tournament:</strong>
  <%= @participation.tournament_id %>
</p>

<p>
  <strong>License:</strong>
  <%= @participation.license %>
</p>

<p>
  <strong>Ranking:</strong>
  <%= @participation.ranking %>
</p>

<%= link_to 'Edit', edit_participation_path(@participation) %> |
<%= link_to 'Back', participations_path %>