config/routes.rb
Rails.application.routes.draw do
 
  resources :participations
  resources :locations
  resources :tournaments
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :rec_password, :only => [:new, :create]

  root 'tournaments#index'

  match '/signup', to: 'users#new', via:'get'
  match '/signin', to: 'sessions#new', via:'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/verify', to: 'users#accountVerification', via: 'get'
  match '/pass', to: 'rec_password#new', via: 'get'
  match '/reset', to: 'rec_password#reset', via: 'get'
  match '/resetAction', to: 'rec_password#resetAction', via: 'post'
  match '/sponsor', to: 'tournaments#sponsor', via: 'post'
  match '/sponsor/:id', to: 'tournaments#sponsorDelete', via: 'delete'
  match '/join', to: 'tournaments#new_join', via: 'get'
  match '/join', to: 'tournaments#create_join', via: 'post'
  match '/participation/:id', to: 'tournaments#leftTournament', via: 'delete'
  match '/my_tournaments', to: 'tournaments#my', via: 'get'
  match '/start', to: 'tournaments#start', via: 'get'
  match '/matches', to: 'tournaments#showMatches', via: 'get' 
  match '/nextRound', to: 'tournaments#nextRound', via: 'post'
end

app/models/user.rb
class User < ActiveRecord::Base

	#Tutaj te wszystkie zależności między tabelami itd.
    has_many :participant, dependent: :nullify #:destroy, :delete_all, :nullify, :restrict_with_error, :restrict_with_exception
    has_many :promoter
    has_one :participant
	
	##

	#przed zapisem w bazie, wszytskie litery w adresie email są zamieniane na małe
	before_save { self.email = email.downcase }
	
	#Tutaj zaczyna się walidacja danych przy rejestracji
	validates :name, presence: true, length: { maximum: 50 }
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:   true,
				        format:     { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }
	
	has_secure_password
	validates :password, length: { minimum: 6 }
	##

	#Te funkcje związane są z bezpieczeństwem po zalogowaniu, generują jakieś losowe ciągi znaków, które są zapisywane w ciasteczkach po zalogowaniu. Chodzi o to żeby nikt nie przejął sesji innego użytkownika po zalogowaniu. FunJeszcze do poczytania na ten temat ;)	
	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.digest(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end
	##


  private
	def create_remember_token
    	self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#Wyświetlamy widok  do rejestracji
  def new
    @user = User.new
  end

	#To wyświetla widok po zalogowaniu użytkownika
  def show
  end
	
  #funkcja przekazuje dane do formularza do edycji danych profilowych
  def edit
  	set_user
  end

  #To się wykonuje, gdy zatwierdzimy zmienione dane na formularzu
  def update
	set_user
    if @user.update_attributes(user_params)
	  #To przekazuje napis do ramki, że wszystko poszło ok
      flash[:success] = "Profile updated"
	  #Przekieruj nas do show.html.erb
      redirect_to @user
    else
		#Jak coś pójdzie żle to wyświetl znowu stronę do edycji
      render 'edit'
    end
  end
 
	#Ta funkcja jest wywoływana, gdy zatwierdzimy rejestrację 
  def create
    @user = User.new(user_params)
	if @user.save
		
		#Te pola są używane podczas weryfikacji maila
		@user.update_attribute(:verification_token, User.new_remember_token)
		@user.update_attribute(:verification_email_sent_at, Time.now)
		##
		#Wysyłamy maila
		VerifyMailer.send_email(@user)
		flash[:success]="Verifying e-mail has been sent"
		render 'show'	
	else
		render 'new'
	end
  end

  def destroy
	set_user
	sign_out
    @user.destroy
	flash[:success]="Profile deleted"
	redirect_to root_url
  end

  def accountVerification
	if(verifyEmail(params['user_id']))		  
		flash.now[:success]="Your account has been activated, you can sign in now"
	else
		flash[:error]="Url not found"
		redirect_to root_url
  	end
  end

  private
    
  	def set_user
      @user = User.find(params[:id])
    end

	def verifyEmail(param)
		user=User.find_by(verification_token: params['user_id'])
		if user && user.verification_token!=nil
			user.update_attribute(:verification_token, nil)
			user.update_attribute(:verification_email_sent_at, nil)
			user.update_attribute(:verified_at, Time.now)
			true
		else
			false
		end
	end	

    def user_params
      params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!--Widok dla edycji profilu -->

<h1>Update profile</h1>		
<div class="row">
  <div class="span6 offset3"> <br>
	<%= form_for(@user) do |f| %>
    	<%= f.label :name %>
    	<%= f.text_field :name %>
	
		<%= f.label :surname %>
	   	<%= f.text_field :surname %>
	
		<%= f.label :email %>
    	<%= f.text_field :email %>
	
		<%= f.label :password %>
		<%= f.password_field :password%>
		
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit "Save changes", class: "btn btn-large btn-primary"  %> 
	<% end %>
 </div>
</div>
<%= link_to 'Back', root_url %>

app/views/users/new.html.erb
<!-- Widok dla rejestracji -->

<h1>Sign up</h1>		
<div class="row">
  <div class="span6 offset3">
	<%= form_for(@user) do |f| %>
		<%=render 'shared/error_messages'%>
    	<%= f.label :name %>
    	<%= f.text_field :name %>
	
		<%= f.label :surname %>
	   	<%= f.text_field :surname %>
	
		<%= f.label :email %>
    	<%= f.text_field :email %>
	
		<%= f.label :password %>
		<%= f.password_field :password%>
		
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>
		
		<%= f.submit "Sign up", class: "btn btn-large btn-primary"  %> 
	<% end %>
 </div>
 </div>
<%= link_to 'Back', root_url %>

app/views/users/show.html.erb
<%if signed_in? %>
	<script>
    	$(document).ready(function () {
        	$('.dropdown-toggle').dropdown();
    	});
	</script> 
	<ul class="nav nav-pills">
   	 <li class="active"><%=link_to 'Home',user_url %></li>
   	 <li><%=link_to 'Profile', edit_user_url  %></li>
   	 <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Tournament <b class="caret"></b></a>
        <ul class="dropdown-menu">
			<li><%=link_to 'New Torunament', new_tournament_path %> </li>
	 	</ul>
	</li>
    <li class="dropdown pull-right">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Admin <b class="caret"></b></a>
        <ul class="dropdown-menu">
			<li><%=link_to 'Sign out',signout_path, method: "delete" %> </li>
           	<li><%=link_to 'Remove account',user_url, method: :delete %> </li>
        </ul>
    	</li>
	</ul>
<%else %>
	<script type="text/javascript">
    	window.location.href="/signin"
  	</script>
<%end %>