config/routes.rb
Rails.application.routes.draw do
 
  resources :participations
  resources :locations
  resources :tournaments
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :rec_password, :only => [:new, :create]

  root 'tournaments#index'

  match '/signup', to: 'users#new', via:'get'
  match '/signin', to: 'sessions#new', via:'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/verify', to: 'users#accountVerification', via: 'get'
  match '/pass', to: 'rec_password#new', via: 'get'
  match '/reset', to: 'rec_password#reset', via: 'get'
  match '/resetAction', to: 'rec_password#resetAction', via: 'post'
  match '/sponsor', to: 'tournaments#sponsor', via: 'post'
  match '/sponsor/:id', to: 'tournaments#sponsorDelete', via: 'delete'
  match '/join', to: 'tournaments#new_join', via: 'get'
  match '/join', to: 'tournaments#create_join', via: 'post'
  match '/participation/:id', to: 'tournaments#leftTournament', via: 'delete'
  match '/my_tournaments', to: 'tournaments#my', via: 'get'
  match '/start', to: 'tournaments#start', via: 'get'
  match '/matches', to: 'tournaments#showMatches', via: 'get' 
  match '/nextRound', to: 'tournaments#nextRound', via: 'post'
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  validates :name, :location_id, :time, :deadline, presence: true
  validates :limit, numericality: { greater_than: 0 }
  validates :seeded_player, numericality: { greater_than_or_equal_to: 0 }
  validates :name, uniqueness: true
  validate :deadline_not_after_time
  validate :seeded_smaller_then_limit
  validate :time_in_future
  validate :deadline_in_future

  belongs_to :promoter
  has_many :rounds
  has_many :participant
  has_one :location

  private

  def deadline_not_after_time
    unless deadline != nil and time != nil and deadline <= time
      errors.add(:deadline, "cannot be after the tournament") 
    end
  end 

  def seeded_smaller_then_limit 
    unless seeded_player != nil and limit != nil && seeded_player <= limit/2
      errors.add(:seeded, "must be smaller then limit of players") 
    end
  end 

  def time_in_future 
    unless time != nil and time > (Time.now + 2*60*60)
      errors.add(:time, "must refer to the future") 
    end
  end

  def deadline_in_future 
    unless deadline != nil and deadline > (Time.now + 2*60*60)
      errors.add(:deadline, "must refer to the future") 
    end 
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
 
  def index
    @tournaments = Tournament.all.paginate(page: params[:page], per_page: 10)
  end

  def my
    @tournaments = Tournament.where(id: (Participation.where(user_id: current_user.id))).paginate(page: params[:page], per_page: 10)
  end

  def new
    if signed_in?	
      @tournament = Tournament.new
      @location = Location.new
    else
      flash[:error] = "You have to be signed in to create a new tournament!"
      redirect_to signin_path
    end
  end

  def new_join
    if signed_in? 
      if Participation.where(tournament_id: session[:id], user_id: current_user.id).count > 0
        flash[:error] = "You have already joined this tournament!"
        redirect_to Tournament.find(session[:id])
      else
        @participation = Participation.new
      end
    else
      flash[:error] = "You have to be signed in to join to the tournament!"
      redirect_to signin_path
    end
  end

  def create_join
    if Participation.where(tournament_id: session[:id]).count < Tournament.find(session[:id]).limit
      @participation = Participation.new 
      @participation.user_id = current_user.id
      @participation.tournament_id = session[:id]
      @participation.ranking = params[:participant][:ranking]
      @participation.license = params[:participant][:license]

      if @participation.save
        flash[:success] = "Joined tournament."
        redirect_to '/tournaments'+'/'+session[:id].to_s
      else
        respond_to do |format|
          format.html { render :new_join }
          format.json { render json: @participant.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:error] = "You cannot join tournament. Number of participants is full."
      redirect_to '/tournaments'+'/'+session[:id].to_s
    end
  end

  def leftTournament
    tournament=Tournament.find_by_id(session[:id])
    Participation.find_by_id(params[:id]).destroy
    redirect_to tournament
  end 

  def show 
    set_tournament
	generateNextRound(@tournament.id)
    @participations = Participation.all
    session[:id]=@tournament.id
    @spons=Sponsor.new
    @sponsors=TournamentSponsor.all
    @json = Location.find(@tournament.location_id).to_gmaps4rails
  end

  def edit
    if signed_in? 
      set_tournament
      if @tournament.deadline > Time.now + 2*60*60
        if @tournament.promoter_id != current_user.id
          flash[:error] = "You can edit only your tournaments!"
          redirect_to root_url
        end
      else
          flash[:error] = "You cannot edit tournament which deadline refers to the past!"
          redirect_to root_url
      end
    else
      flash[:error] = "You have to be signed in to edit your tournament!"
      redirect_to signin_path
    end
  end

  def create
      @tournament = Tournament.new(tournament_params)

      @location = Location.new
      @location.address = params[:tournament][:location_id]
      geocoder = Geocoder.search(@location.address)
      if(geocoder[0].nil?)
        @location.longitude = -1
        @location.latitude = -1
        @location.gmaps = false
      else
        @location.longitude = geocoder[0].longitude
        @location.latitude = geocoder[0].latitude
        @location.gmaps = true
      end

      if @location.save 
        location_saved = true
      else
        location_saved = false
      end

      if @tournament.save
        tournament_saved = true
      else
        tournament_saved = false
      end

      if tournament_saved and location_saved
        @tournament.update_attribute(:promoter_id, current_user.id)
        @tournament.update_attribute(:location_id, @location.id)
        flash[:success]="Tournament created"
        redirect_to root_url
      else
        if tournament_saved
          @tournament.delete
        end
        if location_saved = true
          @location.delete
        end

        respond_to do |format|
          format.html { render :new }
          format.json { render json: @tournament.errors, status: :unprocessable_entity }
        end
      end
  end

  def update
      set_tournament

      #location changed
      if @location.address != params[:tournament][:location_id]
        geocoder = Geocoder.search(params[:tournament][:location_id])
        if(!geocoder[0].nil?)
       	 @location.address = params[:tournament][:location_id]   
          @location.longitude = geocoder[0].longitude
          @location.latitude = geocoder[0].latitude
          @location.gmaps = true
        end
      end

      if @tournament.update(tournament_params) && @location.save
        flash[:success]="Tournament updated"
        @tournament.update_attribute(:location_id,@location.id)
        redirect_to root_url
      else
        @tournament.location_id=@location.id
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: @tournament.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    set_tournament
    Location.find(@tournament.location_id).destroy
    @tournament.destroy
    redirect_to root_url
  end

  def sponsorDelete
    tournament=Tournament.find_by_id(session[:id])
    TournamentSponsor.find_by_id(params[:id]).destroy
    redirect_to tournament
  end

  def sponsor
    extension=nil
    @spons=Sponsor.find_by_name(params[:sponsor][:name])
    if @spons==nil
      @spons=Sponsor.new
      @spons.name=params[:sponsor][:name]
      if params[:sponsor][:img]!=nil
		tmp=params[:sponsor][:img].original_filename.split(".")
		if !tmp[1].nil?
        	extension=tmp[1]
		else
			extension="png"
		end
        @spons.logo="/images/"+@spons.name+"."+extension
      end
      if @spons.save
        tournamentSponsor=TournamentSponsor.new
        tournamentSponsor.tournament_id=session[:id]
        tournamentSponsor.sponsor_id=@spons.id
        tournamentSponsor.save
        if extension!=nil
          filesave(params[:sponsor][:img],@spons.name+"."+extension)
        end
		tournament=Tournament.find_by_id(session[:id])
    	redirect_to tournament
	  else
	  	@tournament=Tournament.find_by_id(session[:id])
		@participations = Participation.all
    	@sponsors=TournamentSponsor.all
		@user=current_user
    	@json = Location.find(@tournament.location_id).to_gmaps4rails
		render :show	
	  end
    else
      tournamentSponsor=TournamentSponsor.new
      tournamentSponsor.tournament_id=session[:id]
      tournamentSponsor.sponsor_id=@spons.id
      tournamentSponsor.save
      if extension!=nil
        filesave(params[:sponsor][:img],@spons.name+"."+extension)
      end
	  tournament=Tournament.find_by_id(session[:id])
      redirect_to tournament
    end
  end
	

  def start
	generateFirstRound(session[:id])
	redirect_to '/matches'
  end

  def showMatches
	current_round=Round.where(:tournament_id => session[:id]).order(phase: :desc).first	
	@matches=Match.where(:round_id=>current_round.id)
  end

  def nextRound
	winner=params[:round][:choose]
	flash[:notify]=winner
	current_round=Round.where(:tournament_id => session[:id]).order(phase: :desc).first	
	current_matches=Match.where(:round_id=>current_round.id)
	match=current_matches.find_by(:playerA=>current_user.id)
	#flash[:notify]=match.id
	#generateNextRound(session[:id],current_round)	
	if !match.nil? 
		if !match.winnerB.nil?
			if match.winnerB==winner.to_i
				match.update_attribute(:participation_id,winner)
				#generateNextRound(session[:id],current_round)
			else 
				match.update_attribute(:winnerB,nil)
			end
		else
			match.update_attribute(:winnerA,winner)
		end
	else
		match=current_matches.find_by(:playerB=>current_user.id)
		if !match.winnerA.nil?
			if match.winnerA==winner.to_i
				match.update_attribute(:participation_id,winner)
				#generateNextRound(session[:id],current_round)
			else 
				match.update_attribute(:winnerA,nil)
			end
		else
			match.update_attribute(:winnerB,winner)
		end
	end
	redirect_to '/matches'	
  end

  private

  def filesave(upload,name) 
    directory = "app/assets/images"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(upload.read) }
  end

  def set_tournament
    if signed_in?
      @user=current_user
    end
    @tournament = Tournament.find(params[:id])
    @location = Location.find(@tournament.location_id)
  end

  def tournament_params
    params.require(:tournament).permit(:name, :promoter_id, :time, :limit, :deadline, :seeded_player,:location_id)
  end

end

app/helpers/tournaments_helper.rb
module TournamentsHelper
	def generateFirstRound(t_id)
		round=Round.new
		round.tournament_id=t_id
		round.phase=1
		round.save
		participants=Participation.where(:tournament_id => t_id).order(:ranking)
		seeded=(1<<(Math.log2(participants.size).to_i+1))-participants.size
		#flash[:notify]=seeded
		i=0; j=seeded+participants.size-1
		while(i<j) do
			if i<seeded
				match=Match.new
				match.playerA=participants[i].user_id
				match.round_id=round.id
				match.save	
			else
				match=Match.new
				match.playerA=participants[i].user_id
				match.playerB=participants[j].user_id
				match.round_id=round.id
				match.save
			end
			i+=1
			j-=1
		end
	end

	def generateNextRound(t_id)
		r=Round.where(:tournament_id => t_id).order(phase: :desc).first
		if !r.nil?	
			matches=Match.where(:round_id=>r.id).size
			winners=Match.where("participation_id IS NOT NULL")
			winners=winners.where(:round_id => r.id).joins(:participation).order("participations.ranking")
			if winners.size == matches
				round=Round.new
				round.tournament_id=t_id
				round.phase=r.phase+1
				round.save
				i=0; j=winners.size-1
				while(i<j) do
					match=Match.new
					match.playerA=winners[i].participation_id
					match.playerB=winners[j].participation_id
					match.round_id=round.id
					match.save
					i+=1
					j-=1
				end
			end	
		end	
	end
end

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :discipline %><br>
    <%= f.text_field :discipline %>
  </div>
  <div class="field">
    <%= f.label :promoter %><br>
    <%= f.text_field :promoter %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.date_select :time %>
  </div>
  <div class="field">
    <%= f.label :limit %><br>
    <%= f.text_field :limit %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :seeded_player %><br>
    <%= f.text_field :seeded_player %>
  </div>
  <div class="field">
    <%= f.label :sponsor %><br>
    <%= f.text_field :sponsor %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Update tournament</h1>		

<% if @tournament.errors.count > 0 || (@location.longitude == -1 && @location.latitude == -1) %>
  <div class="control-group">
    <div class="container">  
      <div class="row">  
        <div class="span6 offset3">  
          <div class="alert alert-error">  
            <% if @location.longitude == -1 && @location.latitude == -1 %>
              <h4 class="text-danger" align="center"><%= pluralize(@tournament.errors.count+1, "error") %> prohibited:</h4>
            <% else %>
              <h4 class="text-danger" align="center"><%= pluralize(@tournament.errors.count, "error") %> prohibited:</h4>
            <% end %>
            <ul>
              <% @tournament.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
              <% if @location.longitude == -1 && @location.latitude == -1 %>
                <li> Adress doesn't exists</li>
              <% end %>
            </ul>
         </div>  
       </div>  
     </div>  
    </div>  
  </div>  
<% end %>

<div class="row">
  <div class="span6 offset3"> <br>
	<%= form_for(@tournament) do |f| %>
		<%= f.label "Name of tournament" %>
    	<%= f.text_field :name %>
	
		<%= f.label "Address" %>
		<%= f.text_field :location_id, :value => Location.find(@tournament.location_id).address %>
		
    <%= f.label "Time of event" %>
    <div id="datetimepicker_time" class="input-append date">
        <%= f.text_field :time, "data-format"=>"dd/MM/yyyy hh:mm", :value => (@tournament.time).strftime('%d/%m/%Y %H:%M') %>
        <span class="add-on">
             <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
    </div>

    <%= f.label "Deadline for signing up" %>
    <div id="datetimepicker_deadline" class="input-append date">
        <%= f.text_field :deadline, "data-format"=>"dd/MM/yyyy hh:mm", :value => (@tournament.deadline).strftime('%d/%m/%Y %H:%M')%>
        <span class="add-on">
             <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
    </div>

		<%= f.label "Limit of participants" %>
		<%= f.text_field :limit %>
		
		<%= f.label "Number of seeded players" %>
        <%= f.text_field :seeded_player %>

		<%= f.submit "Save changes", class: "btn btn-large btn-primary"  %> 
	<% end %>
 </div>
</div>

<%= link_to "Back", root_url %>

<script type="text/javascript">
  $(function() {
    $('#datetimepicker_time').datetimepicker({
      language: 'pt-BR'
    });
    $('#datetimepicker_deadline').datetimepicker({
      language: 'pt-BR'
    });
  });
</script>

app/views/tournaments/index.html.erb
  <h1>Tournaments</h1>

  </br>
  <% if signed_in? %>
    <%= link_to "New tournament", '/tournaments/new' %>
  <% end %>
  </br>
  </br>

  <table align="center">
    <tr><td>
    <table class="table table-hover">
        <tr>
            <th>Tournament name</th>
            <th>Address</th>
            <th>Time</th>
        </tr>
        <% @tournaments.each do |tournament| %>
				<tr data-link=<%=tournament_path(tournament) %> >
                <td><%= tournament.name %></td>
                <td><%= (Location.find((tournament.location_id))).address %></td>
                <td><%= (tournament.time).strftime('%d/%m/%Y %H:%M') %></td>
            </tr>
        <% end %>
    </table>
    </td><td>
    <table class="table">
      <tr><td height=37></td><td></td></tr>
      <% @tournaments.each do |tournament| %>
        <tr>
          <!-- edit and delete -->
          <% if signed_in? && tournament.promoter_id == current_user.id && tournament.deadline > (Time.now+2*60*60) %>
            <td height=37><%= link_to raw('<i class="icon-edit"></i>'), edit_tournament_path(tournament)%> </td>
            <td>
              <%= link_to raw('<i class="icon-trash"></i>'), tournament, method: :delete, 
                data: { confirm: 'Are you sure you want to delete this tournament?'} %>
            </td>
          <% else %>
            <td height=37></td>
            <td></td>
          <% end %>
        </tr>
      <% end %>

    </table>
  </table>

  <%= will_paginate %>

  <script>
	$.fn.twitter_bootstrap_confirmbox.defaults.title = "Delete tournament";
	jQuery(function($) {
    	$("tr[data-link]").click(function() {
        window.location = this.dataset.link
    	});
	})
  </script>

app/views/tournaments/my.html.erb
  <h1>My tournaments</h1>

  </br>
  <% if signed_in? %>
    <%= link_to "New tournament", '/tournaments/new' %>
  <% end %>
  </br>
  </br>

  <table align="center">
    <tr><td>
    <table class="table table-hover">
        <tr>
            <th>Tournament name</th>
            <th>Address</th>
            <th>Time</th>
        </tr>
        <% @tournaments.each do |tournament| %>
				<tr data-link=<%=tournament_path(tournament) %> >
                <td><%= tournament.name %></td>
                <td><%= (Location.find((tournament.location_id))).address %></td>
                <td><%= (tournament.time).strftime('%d/%m/%Y %H:%M') %></td>
            </tr>
        <% end %>
    </table>
    </td><td>
    <table class="table">
      <tr><td height=37></td><td></td></tr>
      <% @tournaments.each do |tournament| %>
        <tr>
          <!-- edit and delete -->
          <% if signed_in? && tournament.promoter_id == current_user.id %>
            <td height=37><%= link_to raw('<i class="icon-edit"></i>'), edit_tournament_path(tournament)%> </td>
            <td>
              <%= link_to raw('<i class="icon-trash"></i>'), tournament, method: :delete, 
                data: { confirm: 'Are you sure you want to delete this tournament?'} %>
            </td>
          <% else %>
            <td height=37></td>
            <td></td>
          <% end %>
        </tr>
      <% end %>

    </table>
  </table>

  <%= will_paginate %>

  <%= link_to "Back", root_url %>

  <script>
	$.fn.twitter_bootstrap_confirmbox.defaults.title = "Delete tournament";
	jQuery(function($) {
    	$("tr[data-link]").click(function() {
        window.location = this.dataset.link
    	});
	})
  </script>

app/views/tournaments/new.html.erb
<h1>New tournament</h1>
</br>
</br>

<!-- errors -->  
<% if @tournament.errors.count > 0 || (@location.longitude == -1 && @location.latitude == -1) %>
  <div class="control-group">
    <div class="container">  
      <div class="row">  
        <div class="span6 offset3">  
          <div class="alert alert-error">  
            <% if @location.longitude == -1 && @location.latitude == -1 %>
              <h4 class="text-danger" align="center"><%= pluralize(@tournament.errors.count+1, "error") %> prohibited:</h4>
            <% else %>
              <h4 class="text-danger" align="center"><%= pluralize(@tournament.errors.count, "error") %> prohibited:</h4>
            <% end %>
            <ul>
              <% @tournament.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
              <% if @location.longitude == -1 && @location.latitude == -1 %>
                <li> Adress doesn't exists</li>
              <% end %>
            </ul>
         </div>  
       </div>  
     </div>  
    </div>  
  </div>  
<% end %>

<div class="row">
  <div class="span6 offset3" class="form-group has-error">
    <%= form_for(@tournament) do |f| %>

    <%= f.label "Name of tournament" %>
    <%= f.text_field :name  %>

    <%= f.label "Address" %>
    <% if params[:location_id].nil? %>
      <%= f.text_field :location_id %>
    <% else %>
      <%= f.text_field :location_id, :value => Location.find(@tournament.location_id).address %>
    <% end %>

    <%= f.label "Time of event" %>
    <div id="datetimepicker_time" class="input-append date">
      <%= f.text_field :time, "data-format"=>"dd/MM/yyyy hh:mm"%>
      <span class="add-on">
        <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      </span>
    </div>

    <%= f.label "Deadline for signing up" %>
    <div id="datetimepicker_deadline" class="input-append date">
      <%= f.text_field :deadline, "data-format"=>"dd/MM/yyyy hh:mm"%>
      <span class="add-on">
        <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      </span>
    </div>

    <%= f.label "Limit of participants" %>
    <%= f.text_field :limit %>

    <%= f.label "Number of seeded players" %>
    <%= f.text_field :seeded_player %>

    <%= f.submit "Create", class: "btn btn-large btn-primary"  %> 
  <% end %>
  </div>
</div>

<%= link_to "Back", root_url %>

<script type="text/javascript">
  $(function() {
    $('#datetimepicker_time').datetimepicker({
      language: 'pt-BR'
    });
    $('#datetimepicker_deadline').datetimepicker({
      language: 'pt-BR'
    });
  });
</script>

app/views/tournaments/new_join.html.erb
<h1>Join tournament "<%= (Tournament.find(session[:id])).name %>"</h1>
<br>
<br>

<%= form_for :participant, url: join_path  do |f| %>

  <% if @participation.errors.any? %>
    <div class="control-group">
    <div class="container">  
      <div class="row">  
        <div class="span6 offset3">  
          <div class="alert alert-error">  
    <h2><%= pluralize(@participation.errors.count, "error") %> prohibited:</h2>

    <ul>
      <% @participation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  </div>
  </div>
  </div>
  </div>
<% end %>

<div class="row">
  <div class="span6 offset3">  
    <%= f.label :license %>
    <%= f.number_field :license %>

    <%= f.label :ranking %>
    <%= f.number_field :ranking %>

    <%= f.submit "Join", class: "btn btn-large btn-primary" %>
  </div>
</div>

<% end %>

app/views/tournaments/show.html.erb
<h1>Tournament details</h1>
</br>

<% if signed_in? %>
  <% if @participations.where(user_id: current_user.id, tournament_id: @tournament.id)[0].nil? %>
    <%= link_to 'Join', join_path  %> 
  <% else %>
    <%row=@participations.where(user_id: current_user.id, tournament_id: @tournament.id)[0]%>
	<%= link_to 'Left', '/participation/'+row.id.to_s, method: :delete  %>
	<%if @tournament.time<Time.zone.now%>
		<%= link_to 'Current matches', matches_path %>
	<%end%>
  <% end %>
<% end %>

</br>

<table align="center">
  <tr>
    <td>
      <table align="center">
        <col width="300">
        <col width="30">
        <col width="300">
        <tr>
          <td align="right">Name</td>
          <td>     </td>
          <td><span style="font-weight:bold"><%=@tournament.name %></span></td>
        </tr>
        <tr> 
          <td align="right">Address</td> 
          <td></td>
          <td><span style="font-weight:bold"><%= (Location.find((@tournament.location_id))).address %></span></td>
        </tr>
        <tr> 
          <td align="right">Time of event</td> 
          <td></td>
          <td><span style="font-weight:bold"><%=(@tournament.time).strftime('%d/%m/%Y %H:%M') %></span></td>
        </tr>
        <tr> 
          <td align="right">Deadline for signing up</td> 
          <td></td>
          <td><span style="font-weight:bold"><%=(@tournament.deadline).strftime('%d/%m/%Y %H:%M') %></span></td>
        </tr>
        <tr> 
          <td align="right">Limit of participants</td> 
          <td></td>
          <td><span style="font-weight:bold"><%=@tournament.limit %></span></td>
        </tr>
        <tr> 
          <td align="right">Number of seeded players</td> 
          <td></td>
          <td><span style="font-weight:bold"><%=@tournament.seeded_player %></span></td>
        </tr>
        <tr>
          <td align="right">Promoter</td>
          <td></td>
          <td><span style="font-weight:bold">
              <%=(User.find((@tournament.promoter_id))).name %> <%=(User.find((@tournament.promoter_id))).surname %>
          </span></td>
        </tr>
      </table>
    </td>
    <td>
      <%= gmaps("markers" => {"data" => @json}, "map_options" => 
                {"processing" => "json", "auto_adjust" => true, "auto_zoom" => false, "zoom" => 15}) %>
    </td>
  </tr>
</table>

<!-- table with sponsors -->
<div class="span3">
<table class="table table-condensed">
	<%if @sponsors!=nil%>
		  <%@sponsors.each do |f| %>
			<%if f.tournament_id==@tournament.id%>
				<tr>
					<td><b><%=f.sponsor.name%></b></td>
					<%if f.sponsor.logo!=nil%>
						<td><%=image_tag f.sponsor.logo.split("/")[2], size: "100" %></td>
					<%else%>
						<td></td>
					<%end%>
					<%if signed_in? && @user.id==@tournament.promoter_id %>
            <td><%=link_to 'delete', '/sponsor/'+f.id.to_s, method: :delete, 
              data: { confirm: 'Are you sure you want to delete this sponsor?' }%>
					<%end%>
				</tr>
			<%end%>
		  <%end%>
  	<%end%>
</table>

<!-- add new sponsor -->
<div class="container">
<%if signed_in? && @user.id==@tournament.promoter_id%>
	<%=form_for :sponsor, url: sponsor_path do |f| %>
	<%=render 'shared/error_sponsors'%>
    <%= f.label "Sponsor" %>
    <%= f.text_field :name, class: 'span4' %> 
	<!--<%= f.file_field :img, accept: 'image/png, image/jpg,image/jpeg, image/gif' %> <br>-->
    <%= f.file_field :img %> <br>
    <%= f.submit "Add", class: "btn btn-large btn-primary"  %> 
	<%end%>
<%end%>
</div>

<!-- delete sponsor confirmation -->
<script>
  $.fn.twitter_bootstrap_confirmbox.defaults.title = "Delete sponsor";
  jQuery(function($) {
    $("tr[data-link]").click(function() {
      window.location = this.dataset.link
    });
  })
</script>

<%= link_to "Back", root_url %>
</div>

app/views/tournaments/showMatches.html.erb
<%if signed_in?%>
<%@matches.each do |f|%>
<div class="span6">
	<table class="table table-hover">
	<tr>
		<td><%=f.playerA%></td>
		<td>VS.</td>
		<td><%=f.playerB%></td>
		<%if f.playerA==current_user.id || f.playerB==current_user.id%>
		<%=form_for :round, url: nextRound_path  do |d| %>
			<td><%=d.select :choose, options_for_select([f.playerA,f.playerB])%></td> 
			<%= d.submit "Confirm", class: "btn btn-large btn-primary" %>
		<%end%>
		<%end%>
	</tr>
	</table>
<%end%>
<%=link_to 'Back', '/tournaments/'+session[:id].to_s%>
</div>
<%else%>
	<script type="text/javascript">
    	window.location.href="/signin"
  	</script>
<%end%>